name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "91b2afea-9cf6-4830-91d0-55cba4f76dc4"
database_name = "memos-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "9430f7cd8f284161a1cf0a2ed8bc690f"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
